"""made lastname nullable

Revision ID: 8649a88a0f17
Revises: ed6fd5af92ef
Create Date: 2023-09-03 13:35:18.764870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8649a88a0f17'
down_revision: Union[str, None] = 'ed6fd5af92ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
